version: '3'
services:
    recipes-api:
        container_name: recipes
        build: .
        environment:
            - SPRING_PROFILES_ACTIVE=prd
            - MYSQL_SERVER=db
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=recipes
            - MYSQL_USER=root
            - MYSQL_PASSWORD=qwe123
        networks:
          - recipe-compose-network
        ports:
          - "8080:8080"
        depends_on:
          - db
    db:
      image: mariadb:10.3.8-bionic
      restart: always
      environment:
          - MYSQL_ROOT_PASSWORD=qwe123
          - MYSQL_DATABASE=recipes
      networks:
        - recipe-compose-network
      ports:
        - "3306:3306"
networks:
  recipe-compose-network:
    driver: bridge